create table if not exists `t_token_price` (
  `f_id` bigint(20) unsigned not null auto_increment comment '自增主键',
  `f_chain_id` int(4) not null comment '链id',
  `f_addr` varchar(125) collate utf8mb4_unicode_ci not null comment '代币合约地址',
  `f_symbol` varchar(25) collate utf8mb4_unicode_ci default null comment '代币符号',
  `f_type1` varchar(125) collate utf8mb4_unicode_ci default null comment '一级类型: cex or dex',
  `f_type2` varchar(125) collate utf8mb4_unicode_ci default null comment '一级类型: blockcc or uniswap or mdex-swap or sushi-swap',
  `f_price` decimal(65,18) default null comment '单价',
  `f_price_change` decimal(16,8) default null comment '24小时价格变化',
  `f_price24high` decimal(36,18) default null comment '24小时最高',
  `f_price24lower` decimal(36,18) default null comment '24小时最低',
  `f_one_day_volume_usd` decimal(65,18) default null comment '24小时交易量',
  `f_total_supply_usd` decimal(65,18) default null comment '总市值',
  `f_total_supply_rank` int(4) default null comment '总市值排名',
  `f_priority` varchar(25) collate utf8mb4_unicode_ci default null comment '币价来源优先级',
  `f_timestamps` bigint(20) default null comment '价格时间',
  `f_platform` varchar(45) collate utf8mb4_unicode_ci default null comment '支持的平台',
  `f_created_at` timestamp(3) null default null comment '创建时间',
  primary key (`f_id`),
  unique key `uniq_chaid_addr` (`f_chain_id`,`f_addr`) using btree
) engine=innodb auto_increment=1651338 default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='代币价格信息表';
