ARG GO_VERSION=1.19

FROM golang:${GO_VERSION}-alpine AS builder

RUN apk update && apk add alpine-sdk git && rm -rf /var/cache/apk/*

RUN mkdir -p /dist
WORKDIR /dist

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
#RUN go build -o ./app ./main.go

ENTRYPOINT ["/bin/sh", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]


