
my-cacheKey:
  cache1: ___mykey1_local
  cache2: ___mykey2_local
  cache3: ___mykey3_local

Reverse-Proxy:
  - 
    from: /a/scan-api
    to: /scan-api
    remotes: 
      - http://172.16.197.233:8080
      - http://172.16.197.134:8080
  - 
    from: /e/scan-api
    to: /scan-api
    remotes: 
      - http://172.16.197.233:8080
      - http://172.16.197.134:8080
  - 
    from: /f/scan-api
    to: /scan-api
    remotes: 
      - http://172.16.197.233:8080
      - http://172.16.197.134:8080
